# Generated by Django 5.1.5 on 2025-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("categories", models.JSONField()),
                ("description", models.TextField()),
                ("original_price", models.IntegerField()),
                ("is_on_sale", models.BooleanField(default=False)),
                ("sale_price", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, default=0)),
                ("cover_image", models.ImageField(upload_to="book_covers/")),
            ],
        ),
    ]
